# Generated by Django 2.0.2 on 2018-02-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('estado', models.BooleanField(default=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=30, unique=True)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('numeroCelular', models.CharField(max_length=10)),
                ('numeroTelefono', models.CharField(max_length=7)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=30, unique=True)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('numeroCelular', models.CharField(max_length=10)),
                ('numeroTelefono', models.CharField(max_length=7)),
                ('email', models.EmailField(max_length=254)),
                ('fotografia', models.ImageField(upload_to='../imagenes/empleados/')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('estado', models.BooleanField(default=False)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionVehiculos.Catalogo')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionVehiculos.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placas', models.CharField(max_length=7, unique=True)),
                ('chasis', models.CharField(max_length=30, unique=True)),
                ('fotografia', models.ImageField(upload_to='../imagenes/catalogoVehiculos/')),
                ('caracteristicas', models.ManyToManyField(related_name='caracteristicasVehiculo', to='GestionVehiculos.ItemCatalogo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcaVehiculo', to='GestionVehiculos.ItemCatalogo')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionVehiculos.Vehiculo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.ManyToManyField(to='GestionVehiculos.ItemCatalogo'),
        ),
    ]
